#!/usr/bin/env sh
echo "Running pre-commit checks..."

if git diff --cached --name-only --diff-filter=ACMRT | grep -Eq '\\.(ts|tsx|json|md)$'; then
  bun lint-staged || exit 1
else
  echo "No staged files for lint-staged."
fi

echo "Type checking..."
bun run typecheck || exit 1

echo "Pre-commit checks passed."
